/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.com.onsys.entidades.marketplace;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRootName;
import io.swagger.annotations.ApiModelProperty;

/**
 * Attributes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
@JsonRootName(value = "item")
public class MELIFreteItem {

    @JsonProperty("seller_id")
    private String seller_id = null;
    
    @JsonProperty("item_id")
    private String item_id = null;
    
    @JsonProperty("store_id")
    private String store_id = null;

    @JsonProperty("sku")
    private String sku = null;
    
    @JsonProperty("quantity")
    private int quantity  = 0;
    
    @JsonProperty("origin")
    private String origin  = null;
    
    @JsonProperty("price")
    private float price = 0;
    
    @JsonProperty("dimensions")
    private MELIFreteDimensions dimensions  = null;  
   
    @ApiModelProperty(value = "")
    public String getSeller_id() {
        return seller_id;
    }

    public void setSeller_id(String seller_id) {
        this.seller_id = seller_id;
    }

    @ApiModelProperty(value = "")    
    public String getItem_id() {
        return item_id;
    }

    public void setItem_id(String item_id) {
        this.item_id = item_id;
    }

    @ApiModelProperty(value = "")
    public String getStore_id() {
        return store_id;
    }

    public void setStore_id(String store_id) {
        this.store_id = store_id;
    }

    @ApiModelProperty(value = "")    
    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    @ApiModelProperty(value = "")        
    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @ApiModelProperty(value = "")        
    public String getOrigin() {
        return origin;
    }

    public void setOrigin(String origin) {
        this.origin = origin;
    }

    @ApiModelProperty(value = "")
    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    @ApiModelProperty(value = "")    
    public MELIFreteDimensions getDimensions() {
        return dimensions;
    }

    public void setDimensions(MELIFreteDimensions dimensions) {
        this.dimensions = dimensions;
    }
    
  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}