/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.onsys.entidades.marketplace;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRootName;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Attributes;

import java.util.List;
import java.util.Objects;

/**
 * ItemJson
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-14T10:44:34.055-03:00")
@JsonRootName(value = "product")
public class MELIProduct {
  @JsonProperty("listing_type_id")
  private String listingTypeId = null;

  @JsonProperty("pictures")
  private List<MELIPictures> pictures = null;

  @JsonProperty("attributes")
  private List<Attributes> attributes = null;

  @JsonProperty("title")
  private String title = null;

//  @JsonProperty("description")
//  private String description = null;
  
  @JsonProperty("description")
  private MELIPlainText description = null;  
  
//  @JsonProperty("warranty")
//  private String warranty = null;
    
  @JsonProperty("available_quantity")
  private Integer availableQuantity = null;

  @JsonProperty("category_id")
  private String categoryId = null;

  @JsonProperty("buying_mode")
  private String buyingMode = null;

  @JsonProperty("currency_id")
  private String currencyId = null;

  @JsonProperty("condition")
  private String condition = null;

  @JsonProperty("site_id")
  private String siteId = null;

//  @JsonProperty("price")
//  private Integer price = null;
  @JsonProperty("price")
  private Double price = null;

  @JsonProperty("official_store_id")
  private Integer officialStoreId = null;

  public MELIProduct listingTypeId(String listingTypeId) {
    this.listingTypeId = listingTypeId;
    return this;
  }

  /**
   * Get listingTypeId
   * @return listingTypeId
   **/
  @ApiModelProperty(value = "")
  public String getListingTypeId() {
    return listingTypeId;
  }

  public void setListingTypeId(String listingTypeId) {
    this.listingTypeId = listingTypeId;
  }

  @ApiModelProperty(value = "")
    public MELIPlainText getDescription() {
        return description;
    }

    public void setDescription(MELIPlainText description) {
        this.description = description;
    }

//    @ApiModelProperty(value = "")
//    public String getWarranty() {
//        return warranty;
//    }

//    public void setWarranty(String warranty) {
//        this.warranty = warranty;
//    }
  
  public MELIProduct title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public MELIProduct availableQuantity(Integer availableQuantity) {
    this.availableQuantity = availableQuantity;
    return this;
  }

  /**
   * Get availableQuantity
   * @return availableQuantity
   **/
  @ApiModelProperty(value = "")
  public Integer getAvailableQuantity() {
    return availableQuantity;
  }

  public void setAvailableQuantity(Integer availableQuantity) {
    this.availableQuantity = availableQuantity;
  }

  public MELIProduct categoryId(String categoryId) {
    this.categoryId = categoryId;
    return this;
  }

  /**
   * Get categoryId
   * @return categoryId
   **/
  @ApiModelProperty(value = "")
  public String getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(String categoryId) {
    this.categoryId = categoryId;
  }

  public MELIProduct buyingMode(String buyingMode) {
    this.buyingMode = buyingMode;
    return this;
  }

  /**
   * Get buyingMode
   * @return buyingMode
   **/
  @ApiModelProperty(value = "")
  public String getBuyingMode() {
    return buyingMode;
  }

  public void setBuyingMode(String buyingMode) {
    this.buyingMode = buyingMode;
  }

  public MELIProduct currencyId(String currencyId) {
    this.currencyId = currencyId;
    return this;
  }

  /**
   * Get currencyId
   * @return currencyId
   **/
  @ApiModelProperty(value = "")
  public String getCurrencyId() {
    return currencyId;
  }

  public void setCurrencyId(String currencyId) {
    this.currencyId = currencyId;
  }

  public MELIProduct condition(String condition) {
    this.condition = condition;
    return this;
  }

  /**
   * Get condition
   * @return condition
   **/
  @ApiModelProperty(value = "")
  public String getCondition() {
    return condition;
  }

  public void setCondition(String condition) {
    this.condition = condition;
  }

  public MELIProduct siteId(String siteId) {
    this.siteId = siteId;
    return this;
  }

  /**
   * Get siteId
   * @return siteId
   **/
  @ApiModelProperty(value = "")
  public String getSiteId() {
    return siteId;
  }

  public void setSiteId(String siteId) {
    this.siteId = siteId;
  }

//public MELIProduct price(Integer price) {
//    this.price = price;
//    return this;
//  }
//  @ApiModelProperty(value = "")
//  public Integer getPrice() {
//    return price;
//  }

//  public void setPrice(Integer price) {
//    this.price = price;
//  }

  public MELIProduct price(Double price) {
    this.price = price;
    return this;
  }

  @ApiModelProperty(value = "")
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }
  
  
  
  
  public MELIProduct officialStoreId(Integer officialStoreId) {
    this.officialStoreId = officialStoreId;
    return this;
  }

  /**
   * Get officialStoreId
   * @return officialStoreId
   **/
  @ApiModelProperty(value = "")
  public Integer getOfficialStoreId() {
    return officialStoreId;
  }

  public void setOfficialStoreId(Integer officialStoreId) {
    this.officialStoreId = officialStoreId;
  }

    public List<MELIPictures> getPictures() {
        return pictures;
    }

    public void setPictures(List<MELIPictures> pictures) {
        this.pictures = pictures;
    }

    public List<Attributes> getAttributes() {
        return attributes;
    }

    public void setAttributes(List<Attributes> attributes) {
        this.attributes = attributes;
    }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MELIProduct itemJson = (MELIProduct) o;
    return Objects.equals(this.listingTypeId, itemJson.listingTypeId) &&
            Objects.equals(this.pictures, itemJson.pictures) &&
            Objects.equals(this.attributes, itemJson.attributes) &&            
            Objects.equals(this.title, itemJson.title) &&
            Objects.equals(this.availableQuantity, itemJson.availableQuantity) &&
            Objects.equals(this.categoryId, itemJson.categoryId) &&
            Objects.equals(this.buyingMode, itemJson.buyingMode) &&
            Objects.equals(this.currencyId, itemJson.currencyId) &&
            Objects.equals(this.condition, itemJson.condition) &&
            Objects.equals(this.siteId, itemJson.siteId) &&
            Objects.equals(this.price, itemJson.price) &&
            Objects.equals(this.officialStoreId, itemJson.officialStoreId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listingTypeId, pictures, attributes, title, availableQuantity, categoryId, buyingMode, currencyId, condition, siteId, price, officialStoreId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemJson {\n");

    sb.append("    listingTypeId: ").append(toIndentedString(listingTypeId)).append("\n");
    sb.append("    pictures: ").append(toIndentedString(pictures)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    availableQuantity: ").append(toIndentedString(availableQuantity)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    buyingMode: ").append(toIndentedString(buyingMode)).append("\n");
    sb.append("    currencyId: ").append(toIndentedString(currencyId)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    siteId: ").append(toIndentedString(siteId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    officialStoreId: ").append(toIndentedString(officialStoreId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
