/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.com.onsys.entidades.marketplace;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRootName;
import io.swagger.annotations.ApiModelProperty;

/**
 * Attributes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
@JsonRootName(value = "dimensions")
public class MELIFreteDimensions {

    @JsonProperty("length")
    private float length = 0;

    @JsonProperty("width")
    private float width = 0;
    
    @JsonProperty("height")
    private float height = 0;
    
    @JsonProperty("weight")
    private float weight  = 0;

    @ApiModelProperty(value = "")        
    public float getLength() {
        return length;
    }

    public void setLength(float length) {
        this.length = length;
    }

    @ApiModelProperty(value = "")        
    public float getWidth() {
        return width;
    }

    public void setWidth(float width) {
        this.width = width;
    }

    @ApiModelProperty(value = "")        
    public float getHeight() {
        return height;
    }

    public void setHeight(float height) {
        this.height = height;
    }

    @ApiModelProperty(value = "")        
    public float getWeight() {
        return weight;
    }

    public void setWeight(float weight) {
        this.weight = weight;
    }
    
  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}