/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.com.onsys.entidades.marketplace;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRootName;
import io.swagger.annotations.ApiModelProperty;

/**
 * Attributes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
@JsonRootName(value = "item")
public class MELIFreteRetornoItem {

    @JsonProperty("sku")
    private String sku = null;
    
    @JsonProperty("seller_id")
    private String seller_id = null;

    @JsonProperty("quantity")
    private int quantity  = 0;

    @JsonProperty("stock")
    private int stock   = 0;

    @JsonProperty("error_code")
    private int error_code   = 0;
    
    @JsonProperty("store_id")
    private String store_id = null;
    
    @ApiModelProperty(value = "")    
    public int getStock() {
        return stock;
    }

    public void setStock(int stock) {
        this.stock = stock;
    }

    @ApiModelProperty(value = "")    
    public int getError_code() {
        return error_code;
    }

    public void setError_code(int error_code) {
        this.error_code = error_code;
    }
   
    @ApiModelProperty(value = "")
    public String getSeller_id() {
        return seller_id;
    }

    public void setSeller_id(String seller_id) {
        this.seller_id = seller_id;
    }

    @ApiModelProperty(value = "")    
    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    @ApiModelProperty(value = "")
    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @ApiModelProperty(value = "")    
    public String getStore_id() {
        return store_id;
    }

    public void setStore_id(String store_id) {
        this.store_id = store_id;
    }
    
  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}