/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.com.onsys.entidades.marketplace;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRootName;
import io.swagger.annotations.ApiModelProperty;

/**
 * Attributes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
@JsonRootName(value = "quotations")
public class MELIFreteQuotations {

    @JsonProperty("cost")
    private float cost = 0;

    @JsonProperty("price")
    private float price = 0;
    
    @JsonProperty("handling_time")
    private int handling_time = 0;
    
    @JsonProperty("shipping_time")
    private int shipping_time = 0;

    @JsonProperty("promise")
    private int promise  = 0;

    @JsonProperty("caption")
    private String caption  = "Normal";
    
    @JsonProperty("service_id")
    private int service_id   = 0;

    @ApiModelProperty(value = "")    
    public float getCost() {
        return cost;
    }

    public void setCost(float cost) {
        this.cost = cost;
    }

    @ApiModelProperty(value = "")    
    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    @ApiModelProperty(value = "")    
    public int getHandling_time() {
        return handling_time;
    }

    public void setHandling_time(int handling_time) {
        this.handling_time = handling_time;
    }

    @ApiModelProperty(value = "")    
    public int getShipping_time() {
        return shipping_time;
    }

    public void setShipping_time(int shipping_time) {
        this.shipping_time = shipping_time;
    }

    @ApiModelProperty(value = "")    
    public int getPromise() {
        return promise;
    }

    public void setPromise(int promise) {
        this.promise = promise;
    }

    @ApiModelProperty(value = "")    
    public String getCaption() {
        return caption;
    }

    public void setCaption(String caption) {
        this.caption = caption;
    }

    @ApiModelProperty(value = "")    
    public int getService_id() {
        return service_id;
    }

    public void setService_id(int service_id) {
        this.service_id = service_id;
    }
    
  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}